var defaultParams = {
  title: '',
  text: '',
  type: null,
  allowOutsideClick: false,
  showConfirmButton: true,
  showCancelButton: false,
  showThirdButton: false,
  closeOnConfirm: true,
  closeOnThird: true,
  closeOnCancel: true,
  confirmButtonText: 'OK',
  confirmButtonColor: '#8CD4F5',
  thirdButtonColor: '#8CD4F5',
  cancelButtonText: 'Cancel',
  thirdButtonText: 'Third',
  imageUrl: null,
  imageSize: null,
  timer: null,
  customClass: '',
  html: false,
  animation: true,
  allowEscapeKey: true,
  inputType: 'text',
  inputPlaceholder: '',
  inputValue: '',
  showLoaderOnConfirm: false,
  showLoaderOnThird: false
};

export default defaultParams;
